dracut/30ignition/ignition-ask-var-mount.service
dracut/30ignition/ignition-generator
dracut/30ignition/ignition-remount-sysroot.service
dracut/30ignition/module-setup.sh

This new service file adds a special file in `/run` and runs before
`ostree-prepare-root.service` so that the latter mounts `/var` rather
than relying on the OSTree generator post-switchroot.
This also requires us to remount `/var` read-write so that Ignition can
e.g. create new users.

Add ignition-ask-var-mount.service

---

dracut/30ignition/ignition-generator
dracut/30ignition/module-setup.sh

This is another hack like the xen = ec2 one to get RHCOS ignition
working in OpenStack for now. A lot of our infra and scripts currently
interop well with OpenStack, so unblocking this should make it easier to
iterate on testing RHCOS overall.

ignition-generator: add hack for openstack support

---

dracut/30ignition/ignition-generator
dracut/30ignition/module-setup.sh

We now explicitly stamp images for their respective cloud providers so
we no longer need to try to guess.

Drop 'auto-detect' hacks in generator

---

dracut/99journald-conf/00-journal-log-forwarding.conf
dracut/99journald-conf/module-setup.sh

This makes ignition logs show up on ttyS0. Without this option, ignition logs only shows up on tty0.
Related to https://github.com/openshift/os/pull/158

Add Journald 'forward to kernel log buffer' option

---

dracut/99journald-conf/00-journal-log-forwarding.conf

It defaults to notice, which doesn't print out the "info"
level information we want to get from ignition.

change the default level of messages send to kmsg

---

systemd/coreos-firstboot-complete.service

See ostreedev/ostree#1697
Just noticed this while investigating our services after the
recent machine-id regression.

coreos-firstboot-complete: RemainAfterExit=yes

---

dracut/30ignition/module-setup.sh

This drop some legacy/commented line for installing CL-specific udev
rules. We'll likely grow some more bits to install into initramfs in
the future, which should not be part of this ignition module.

dracut/ignition: remove CL-legacy udev references

---

dracut/99journald-conf/00-journal-log-forwarding.conf

if we do that then we get "double logs" on the console device
because both kmsg and console output is getting dumped there.

journal: don't log to console AND kmsg

---

dracut/30ignition/module-setup.sh

Make it explicit that we need the `qemu_fw_cfg` kernel module in the
initramfs. This works for Fedora right now before I think because we run
dracut with `--no-host-only` at compose time. (It's the default if
`initramfs-args` isn't in the manifest, as in FCOS, and in FAH we
explicitly have it in the manifest).
Closes: #22

module-setup.sh: explicitly install qemu_fw_cfg

---

dracut/30ignition/module-setup.sh

Otherwise we'll error out on kernels which have the functionality
builtin. This was tested on FCOS (which uses `m`) and on a kernel which
has it built in (`y`).

30ignition: only instmods if module available

---

dracut/30ignition/ignition-files.service
dracut/30ignition/ignition-remount-sysroot.service
dracut/30ignition/module-setup.sh

Some Linux Distributions don't pass a rw option on the kernel commandline
and thus mount the root filesystem ro by default. In this case, remount
/sysroot to rw (issue #37)

Remount /sysroot rw

---

dracut/99journald-conf/00-journal-log-forwarding.conf

It's good to provide some history so that we can know
when we can drop these changes.

journal: add clarifying comment for context

---

dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-files.service
dracut/30ignition/ignition-generator
dracut/30ignition/ignition-setup.sh
dracut/30ignition/module-setup.sh

This PR lays some ground work for supporting platform configs based on OEM
id and also support for embedded user configs in /boot/ (bare metal install use case).

support platform configs and user configs in /boot

---

dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-files.service
dracut/30ignition/ignition-generator
dracut/30ignition/ignition-setup.sh

With https://github.com/coreos/ignition/pull/735 merged, we need to fix
our service units to use `--platform` here. Also just do the equivalent
thing here and start to move away from the oem terminology. Crucially
though, we still look for `coreos.oem.id` until downstreams have
adapted (notably coreos-assembler).

dracut: adapt for s/oem/platform in Ignition

---

dracut/30ignition/module-setup.sh

This fixes it on not supported arches(i.e. including module that doesn't exist). It will unblock the cosa on all arches that don't support the qemu_fw_cfg(related to the ignition [#666](https://github.com/coreos/ignition/issues/666)). I haven't yet tested this on x86_64. I would much appreciate testing on x86_64 and comments on the general approach.

module-setup.sh: Simplify the qemu_fw_cfg kernel module check

---

grub/02_ignition_firstboot

On UEFI systems the grub $root might be the /boot/efi/
partition and not the /boot/ partition so let's search
for the partition with the `boot` label and then detect
the file directly.
Fixes #51

grub: find boot partition and use it directly

---

grub/02_ignition_firstboot

On UEFI systems the grub $root might be the /boot/efi/
partition and not the /boot/ partition so let's search
for the partition with the `boot` label and then detect
the file directly.
Fixes #51
(cherry picked from commit 552edb5c959bb4a99be6cba15423bf357d016aa8)

spec2x: grub: find boot partition and use it directly

---

dracut/30ignition/ignition-generator

It's true it's only pulled into the transaction right now by the other
services. But just on principle, let's not even write it if we know
we're not going to use it.

dracut/30ignition: Only write ignition-setup.service on first boot

---

dracut/30ignition/ignition-ask-var-mount.service
dracut/30ignition/ignition-complete.target
dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-files.service
dracut/30ignition/ignition-generator
dracut/30ignition/ignition-remount-sysroot.service
dracut/30ignition/ignition-setup.service
dracut/30ignition/module-setup.sh

From the comment block of the unit:
This target is reached when Ignition finishes running. Note that it
gets activated *only* on first boot (or if ignition.firstboot=1 is
provided).  Thus, it is also an API for units to use so that they
are activated only on first boot. Simply add a link under
ignition-complete.target.requires in the initrd.
Thus, units themselves don't need to add explicit `Requires=`; the
canonical way to get pulled into the transaction is through
`ignition-complete.target`.
This will also be used by the upcoming CoreOS units that are required
for separate `/var` support.

Add ignition-complete.target

---

grub/02_ignition_firstboot

Today coreos-assembler is hardcoding the initramfs networking kargs to
do DHCP; this is problematic for e.g. bare metal where one often wants
to configure static networking.
Let's only enable initramfs networking if we're doing Ignition.

02_ignition_firstboot: Enable networking if Ignition will run

---

dracut/30ignition/module-setup.sh

The `ignition` binary is not intended to be run by users or in the real root filesystem, and thus should never be in PATH.  Expect distros to install it into the dracut module directory instead.

dracut/30ignition: expect ignition binary in module directory

---

dracut/30ignition/module-setup.sh
grub/02_ignition_firstboot

This PR contains backports of the following patches in master:
- 738c676 dracut/30ignition: expect ignition binary in module directory
-  c62a108 02_ignition_firstboot: Enable networking if Ignition will run
- 552edb5 grub: find boot partition and use it directly
- 819e0da module-setup.sh: Check for module qemu_fw_cfg not build-in, so it works out of box on all arches

spec2x: backports from master branch

---

grub/02_ignition_firstboot

This allows us to set network kcmdline args by setting the
ignition_network_kcmdline variable inside the ignition.firstboot
file that resides on the /boot/ filesystem and triggers ignition
run on boot.
This functionality will allow the coreos-installer to promote static
networking arguments that were used during the installer run to the
first boot of the real system. After that they are no longer needed
as ignition can configure networking as requested by the user.

grub: support overriding network kcmdline args

---

grub/02_ignition_firstboot

This allows us to set network kcmdline args by setting the
ignition_network_kcmdline variable inside the ignition.firstboot
file that resides on the /boot/ filesystem and triggers ignition
run on boot.
This functionality will allow the coreos-installer to promote static
networking arguments that were used during the installer run to the
first boot of the real system. After that they are no longer needed
as ignition can configure networking as requested by the user.
(cherry picked from commit a65ec1667338518a44c75a21ceb955408c3061da)

spec2x: grub: support overriding network kcmdline args

---

dracut/30ignition/module-setup.sh

The Ignition openstack platform needs to be able to read from a virtual
cdrom and needs to include the uedv rules to create the symlink. Add
those rules.

module_setup: include cdrom rules for openstack

---

dracut/30ignition/module-setup.sh

The Ignition openstack platform needs to be able to read from a virtual
cdrom and needs to include the uedv rules to create the symlink. Add
those rules.

[spec2x] module_setup: include cdrom rules for openstack

---

dracut/30ignition/ignition-complete.target

We shouldn't actually need to do `OnFailure=emergency.target` in
`ignition-complete.service` here. Our unit is already a requirement of
`initrd.target`, and so once we fail, `initrd.target` should fail, which
in turn should trigger *its* `OnFailure=emergency.target`.
However, this doesn't work in f29/el8:
https://bugzilla.redhat.com/show_bug.cgi?id=1696796
Add a comment about that.
See also: https://github.com/coreos/ignition-dracut/pull/61/#issuecomment-475767503

dracut/30ignition: link to RHBZ in ignition-complete

---

dracut/30ignition/ignition-ask-var-mount.service
dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-files.service
dracut/30ignition/ignition-generator
dracut/30ignition/ignition-remount-sysroot.service

Backport of 50d1830.
But we don't have an `ignition-complete.target` here so just add it to
each individual service. Super tempted to just backport everything from
master and just leave off the spec 3.0.0 specific bits, though let's do
the least invasive fix for now.
Note here that we have to add `OnFailureJobMode=isolate` because
otherwise the boot will just keep looping around for a while instead of
crashing:
https://bugzilla.redhat.com/show_bug.cgi?id=1696796
Closes: #59

spec2x: dracut/30ignition: order services before initrd.target 

---

dracut/30ignition/ignition-files.service

This is in spirit a backport of [1]. But it's as relevant on the spec2x
branch.
[1] https://github.com/coreos/ignition-dracut/blob/85f2e6558c5e1651e2934849b8ad1d74a5c7ad74/dracut/30ignition/coreos-populate-var.sh#L36

ignition-files: always relabel /var on first boot

---

dracut/30ignition/coreos-teardown-initramfs-network.service
dracut/30ignition/coreos-teardown-initramfs-network.sh
dracut/30ignition/ignition-generator
dracut/30ignition/module-setup.sh

Add coreos-remove-initramfs-network.service to run after ignition
has finished using initramfs networking, so NetworkManager properly
brings up ignition-configured networking in the real root. Otherwise
the initramfs network persists into the real root.
Signed-off-by: Yu Qi Zhang <jerzhang@redhat.com>

30ignition: remove initramfs networking

---

dracut/99emergency-timeout/module-setup.sh
dracut/99emergency-timeout/timeout.sh

If Ignition fails, instead of immediately dropping to an emergency
shell, output a message indicating that Ignition failed and point
to ignition-validate. Offer to drop to an emergency shell if the
user presses Enter. If the user doesn't respond in 5 minutes,
reboot to try again. While waiting for the timeout, keep updating
the prompt with the time remaining until reboot.
Brought forward from the `99emergency-timeout` dracut module
present in Container Linux: https://github.com/coreos/bootengine/tree/c691205c0046e3828a8536d553aea7307ca3abee/dracut/99emergency-timeout
Closes: #35
---
Minor tweaks were made to the output message:
```diff
diff --git a/bootengine/dracut/99emergency-timeout/timeout.sh b/ignition-dracut/dracut/99emergency-timeout/timeout.sh
index c37bd7b..b678368 100644
--- …
```

dracut: add 99emergency-timeout

---

dracut/99emergency-timeout/module-setup.sh
dracut/99emergency-timeout/timeout.sh

See commit message. Adapted from #85, with the following diff:
```diff
--- a/dracut/99emergency-timeout/timeout.sh
+++ b/dracut/99emergency-timeout/timeout.sh
@@ -29,7 +29,7 @@ _prompt_for_timeout() {
if [[ -e /.emergency-shell-confirmed ]]; then
return
fi
-    ignition_units="ignition-disks.service ignition-files.service ignition-mount.service"
+    ignition_units="ignition-disks.service ignition-files.service"
if systemctl show $ignition_units | grep -q "^ActiveState=failed$"; then
@@ -43,7 +43,7 @@ _prompt_for_timeout() {
cat <<EOF
-------------------------------------------------------------------------------
Ignition has failed. Please ensure your config is valid. Note that only Ignition spec
-v3.0.0+ configs are accepted.
+v2.x.x configs are accepted.
A CLI validation tool to check …
```

[spec2x] dracut: add 99emergency-timeout

---

dracut/30ignition/module-setup.sh
dracut/30ignition/persist-ifcfg.sh
grub/02_ignition_firstboot

When `coreos.no_persist_ip` is specified on the kcmdline delete
`/etc/sysconfig/network-scripts` that was created by the dracut
`write-ifcfg.sh` script before running Ignition. This allows the use
case of configuring only the initial initramfs networking via ip= to
allow fetching of the Ignition config, and specifying a more complex
real root configuration in the Ignition config.

dracut/30ignition: support `coreos.no_persist_ip`

---

dracut/30ignition/module-setup.sh

Given that this isn't causing errors there's probably something else
pulling it in by the correct name, but we ought to include it here as
well for clarity's sake.

dracut/30ignition: fix typo in module_setup

---

dracut/30ignition/persist-ifcfg.sh

We shouldn't persist anything in the default networking case of `ip=dhcp`;
NetworkManager does dhcp by default on connected interfaces by default anyways,
and more importantly doing so can clash if a user provides static IP configuration
via Ignition, as was supported in OpenShift 4.1.  See
https://bugzilla.redhat.com/show_bug.cgi?id=1736875
Closes: https://github.com/coreos/ignition-dracut/issues/96

[spec2x] persist-ifcfg: Don't persist default ip=dhcp

---

dracut/30ignition/persist-ifcfg.sh

For some reason if the script does not have the execute bit on,
dracut just...silently fails. This will cause e.g. rd.break to
not be honored.
cc @arithx

persist-ifcfg: fix early exiting of dracut init script

---

dracut/30ignition/ignition-generator

I'm trying to rebase RHCOS on FCOS (though still Ignition spec 2x).
coreos-assembler git master only generates `ignition.platform.id`,
and we also changed some of the IDs.
RHCOS had some code trying to fix this in a separate dracut
module but it wasn't working - I started to debug it but
it really seems *way* cleaner to just patch the spec2x branch
to honor `ignition.platform.id` directly, so that's what this does.
While here, I also intentionally dropped the bits to auto-detect qemu.
That seems hacky; our qemu images should be stamped qemu.
I also dropped the hardcoding of `pxe` as a default; if nothing is
set, then we don't try to guess.

generator: Use ignition.platform.id if available

---

Makefile

See https://github.com/cgwalters/build-api
With this for example, we can just have the Fedora spec file do
`make install DESTDIR=$RPM_BUILD_ROOT` just like everything else;
helping to ensure that as much logic as possible remains upstream.
Mainly I want this for hacking so I can just
`make install DESTDIR=/srv/walters/fcos/overrides/rootfs`
without building an RPM or copying files manually.

Makefile: New file implementing `make install`

---

dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-files.service

Omitting this can cause the unit to be executed multiple
times if it's a dependency of another unit (as these are).
See https://github.com/ostreedev/ostree/pull/1697
and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=750683

Add RemainAfterExit=yes to systemd units of Type=oneshot

---

dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-fetch.service
dracut/30ignition/module-setup.sh

This invokes the new `fetch` stage which does just that - fetch
the Ignition config into `/run/ignition.json` and nothing else.
Prep for adding support for redeploying the rootfs, which is
an expensive process, so we only want to do it if the fetched
Ignition config is replacing the `rootfs`.

dracut: Add an ignition-fetch.service

---

dracut/30ignition/coreos-gpt-setup@.service
dracut/30ignition/ignition-complete.target
dracut/30ignition/ignition-diskful.target
dracut/30ignition/ignition-remount-sysroot.service

Failed units in `ignition-diskful.target` weren't correctly causing boot failures, since several units weren't properly sequenced `Before` the respective target that was supposed to handle their failure.
I also dug a bit into the need for `ignition-complete.target` to carry its own `OnFailure` declaration.  The test case in [@jlebon's bug](https://bugzilla.redhat.com/show_bug.cgi?id=1696796) no longer works on F30/F31.  Overriding `initrd.target` to `OnFailureJobMode=isolate`, as @jlebon suggested, does avoid the problem.  Since the workaround in `ignition-complete.target` is localized and I believe it to be reliable, I've updated the comment there and am inclined to leave it alone for now.
Part of https://github.com/coreos/fedora-coreos-config/pull/177.

30ignition: Failure handling improvements

---

dracut/30ignition/ignition-disks.service

Make sure to run before the file system checks, as sgdisk will trigger
udev events, potentially resulting in race conditions due to disappearing
devices. Executing earlier will avoid this and hopefully similar problems.
Fixes #114.

Run ignition-disks earlier to avoid race condition

---

dracut/30ignition/ignition-setup.sh

I was just looking at the script and seen $destination could be used
in another place instead of duplicating '/usr/lib/ignition'

30ignition: Minor cleanup to install script

---

dracut/30ignition/coreos-teardown-initramfs-network.sh

`bonding_masters` interface is used by initramfs to start bonding connection and it cannot be brought down cleanly.
This PR would skip this interface during initramfs networking teardown.
Verified that it works with:
Fixes bugzilla.redhat.com/show_bug.cgi?id=1758091

[spec2x]  teardown: skip bonding_masters

---

systemd/ignition-firstboot-complete.service

See: https://github.com/openshift/installer/pull/2554
Basically the OpenShift installer on vSphere injects a service which reboots
the first time, but I believe this could easily race with `ignition-firstboot-complete`.
Let's mark the boot complete much earlier.

ignition-firstboot-complete.service: Run as part of basic.target

---

Makefile

See https://github.com/cgwalters/build-api
With this for example, we can just have the Fedora spec file do
`make install DESTDIR=$RPM_BUILD_ROOT` just like everything else;
helping to ensure that as much logic as possible remains upstream.
Mainly I want this for hacking so I can just
`make install DESTDIR=/srv/walters/fcos/overrides/rootfs`
without building an RPM or copying files manually.
(cherry picked from commit f06c020b3265db6c3377c0d6694b897e99495999)

[spec2x] Makefile: New file implementing `make install`

---

systemd/ignition-firstboot-complete.service

See: https://github.com/openshift/installer/pull/2554
Basically the OpenShift installer on vSphere injects a service which reboots
the first time, but I believe this could easily race with `ignition-firstboot-complete`.
Let's mark the boot complete much earlier.
(cherry picked from commit 598bbdded7c683d22d572bfbf6d76139a86ebd19)

[spec2x] ignition-firstboot-complete.service: Run as part of basic.target

---

Makefile

I had to add this line to skip the `README.txt` that only exists in the `spec2x` branch and...
It silently appeared to work (just didn't install the files),
but I had them already there from a previous run from the
master branch...this resulted in a lost 10 minutes of tracing
down exactly why my changes weren't appearing :cry:

Makefile: Fix spec2x backport mistake

---

dracut/30ignition/persist-ifcfg.sh

This currently runs *after* Ignition, and we shouldn't
overwrite any config files people created that way.
Now in practice, automatic persistence and manual configuration
are probably only sanely mutually exlusive, but let's do the
obviously right thing if someone decides to mix them.

persist-ifcfg: Don't overwrite extant files

---

dracut/30ignition/ignition-fetch.service
dracut/30ignition/ignition-generator
dracut/30ignition/module-setup.sh

This is a backport of the fetch stage but modified for `spec2x`. RHCOS needs the fetch stage to enable encryption.

30ignition: backport of the fetch stage

---

dracut/30ignition/persist-ifcfg.sh

Do it the same way Ignition works on the spec2x branch.
This came up as the NM state operator being unable to modify the files.

persist-ifcfg: Ensure files we write have SELinux labels

---

dracut/30ignition/coreos-gpt-setup.sh

lsblk doesn't have PTUUID in the version on RHEL 8, but we
can get it from blkid.

coreos-gpt-setup: workaround old lsblk not having PTUUID

---

systemd/ignition-firstboot-complete.service

zipl records need to be updated, because ignition.firstboot is burned
into target disk during coreos-installer
As a short-term solution for:
https://github.com/coreos/ignition-dracut/issues/84
Depends on:
https://github.com/ibm-s390-tools/s390-tools/pull/71
https://github.com/ibm-s390-tools/s390-tools/pull/74
Related:
https://github.com/coreos/coreos-installer/pull/61
https://github.com/coreos/coreos-assembler/pull/780

firstboot-complete: tell zipl to run

---

dracut/30ignition/ignition-setup-user.sh

We don't actually need write access to `/boot` here to pull out any
baked Ignition config. Just mount it read-only.
This also helps in the case where any other service is concurrently also
mounting `/boot`: trying to mount a device as read-write that's already
mounted read-only elsewhere will fail. I hit this when playing with FIPS
mode, which does this:
https://github.com/dracutdevs/dracut/blob/718aefda1374c7b6c3790b08cae27fd6bde505af/modules.d/01fips/fips.sh#L49

30ignition/ignition-setup-user: mount /boot partition ro

---

dracut/30ignition/ignition-setup.sh

We don't actually need write access to `/boot` here to pull out any
baked Ignition config. Just mount it read-only.
This also helps in the case where any other service is concurrently also
mounting `/boot`: trying to mount a device as read-write that's already
mounted read-only elsewhere will fail. I hit this when playing with FIPS
mode, which does this:
https://github.com/dracutdevs/dracut/blob/718aefda1374c7b6c3790b08cae27fd6bde505af/modules.d/01fips/fips.sh#L49
(backport of https://github.com/coreos/ignition-dracut/pull/134)

30ignition/ignition-setup: mount /boot partition ro

---

dracut/30ignition/ignition-complete.target
dracut/30ignition/ignition-generator
dracut/30ignition/ignition-mount.service
dracut/30ignition/ignition-subsequent.target
dracut/30ignition/module-setup.sh

Backport: Add `ignition-subsequent.target` for non-Ignition boots
This is needed for Red Hat CoreOS work for encrypted disks. With the CoreOS Assembler commit 8bcd5608c473a959dae240a6488ce3451ddcdc69, the  `root=` and `rootflags` kargs are removed. Red Hat CoreOS is also using b29bf79c5bd27d683519cf2e236f6f9088f6d127 from  Fedora CoreOS that uses a  service to mount and locate the root filesystem on first boot via `ignition-ostree-mount-sysroot.service`. The problem, however, is that there are different dependencies/ordering if we're doing the "Ignition boot" versus a "subsequent" boot.
Add a new target that's queued up if we detect we're doing a "subsequent" boot.

[spec2x] Backport: Add `ignition-subsequent.target` for non-Ignition boots

---

dracut/30ignition/module-setup.sh

This is required by the new relabeling code in Ignition:
https://github.com/coreos/ignition/pull/846
(This is another good example of why merging this repo into
coreos/ignition would be nicer I think.)

30ignition: add setfiles

---

systemd/ignition-firstboot-complete.service

zipl records need to be updated, because ignition.firstboot is burned
into target disk during coreos-installer
As a short-term solution for:
https://github.com/coreos/ignition-dracut/issues/84
Depends on:
https://github.com/ibm-s390-tools/s390-tools/pull/71
https://github.com/ibm-s390-tools/s390-tools/pull/74
Related:
https://github.com/coreos/coreos-installer/pull/61
https://github.com/coreos/coreos-assembler/pull/780
(cherry picked from commit 38af701ac39d9a2f11f9d377f5a5b0168f7a0cb3)

[spec2x] cherry-pick: firstboot-complete: tell zipl to run

---

dracut/30ignition/ignition-complete.target
dracut/30ignition/ignition-subsequent.target

I noticed that several of our units actually run twice, including
`ignition-files.service` (!) and `ignition-ostree-mount-firstboot-sysroot.service`.
Looking deeper into this, I discovered a bit of the initrd that
I didn't even know existed, which is `initrd-parse-etc.service`
that actually runs `ExecStart=-/usr/bin/systemctl --no-block start initrd-fs.target`
*post* switch root, after services that are part of that target
have already run (and then been shut down).
This adds a big wrinkle to my understanding of system bootup.
Then I noticed that `initrd-fs.target` has:
`ConditionPathExists=/etc/initrd-release`
which will be false post-switchroot.
The semantics here are...strange.  It seems like the goal is to ensure
that the rootfs is definitely still mounted, perhaps in
very complex …

Add ConditionPathExists=/etc/initrd-release to targets

---

dracut/30ignition/ignition-generator

Instead of `initrd.target`.  This matches with what happens on
master, and will help ensure that the units aren't rerun as part of
`initrd-parse-etc.service` in concert with adding
`ConditionPathExists=/etc/initrd-release` to the targets.

generator: Bind main Ignition units to ignition-complete.target

---

dracut/30ignition/coreos-gpt-setup@.service
dracut/30ignition/ignition-complete.target
dracut/30ignition/ignition-diskful.target
dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-fetch.service
dracut/30ignition/ignition-files.service
dracut/30ignition/ignition-mount.service
dracut/30ignition/ignition-remount-sysroot.service
dracut/30ignition/ignition-setup-base.service
dracut/30ignition/ignition-setup-user.service
dracut/30ignition/ignition-subsequent.target

This is standard practice for units that are only meant to run in the
initrd. It matches what e.g. `systemd` does for its initrd units. See
also: https://github.com/coreos/ignition-dracut/pull/140.
I also snuck in `Documentation=` lines in there.

units: add ConditionPathExists=/etc/initrd-release everywhere

---

dracut/30ignition/module-setup.sh

To support https://github.com/coreos/ignition/pull/865
Reported-by: XiaoMeiZheng <xmzheng@cn.ibm.com>

dracut: add some bins for s390x zVM instalation

---

dracut/30ignition/module-setup.sh

setfiles is only required on systems using SELinux - on systems without SELinux an error message was shown while building the initrd.

Make setfiles optional

---

dracut/30ignition/coreos-teardown-initramfs-network.sh

Bonded interfaces that were taken down with just `ip link set <if>
down` remained defined in `/sys/class/net/bonding_masters`.  The
presence of these bonded interfaces in that `sysfs` location appears
to confuse `NetworkManager` during first boot and causes the bonded
interfaces to not come up correctly in the real root.
By removing the entries from `bonding_masters`, `NetworkManager` is
able to bring up the bonded interfaces correctly in the real root.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1789601

dracut: down the bonded interfaces properly (BZ#1789601)

---

dracut/30ignition/persist-ifcfg.sh
grub/02_ignition_firstboot

coreos-assembler moved now to `ip=dhcp,dhcp6`, so we need to adapt the
ifcfg persist logic here:
https://github.com/coreos/coreos-assembler/pull/1067
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1793591

Adapt to move to ip=dhcp,dhcp6

---

Makefile

`make install` was failing now that the grub bits are gone.

Makefile: Remove grub/ install bits

---

dracut/30ignition/ignition-diskful-subsequent.target
dracut/30ignition/ignition-generator
dracut/30ignition/module-setup.sh

This target is a combination of `ignition-subsequent.target` and
`ignition-diskful.target` - units here should only run when we have a
boot disk and *aren't* doing the first boot.
This came out of discussion in
https://github.com/coreos/fedora-coreos-config/pull/271
Will be used by FCOS.
Suggested-by: @jlebon

Add ignition-diskful-subsequent.target

---

.cci.jenkinsfile

This is the first repo that we hook up to the new CoreOS CI interface.
And it's sorely needed too, since patches here can easily result in
broken boots.

Hook up to CoreOS CI

---

dracut/30ignition/persist-ifcfg.sh

This resolves the problem where `ip=...` defines a hostname but the hostname is not persisted.

Persist the first-boot hostname if not otherwise set

---

dracut/30ignition/module-setup.sh

When trying to reduce the size of the initrd we noticed that several dependencies in the dracut setup script are obsolete (first commit) or inconsistently flagged as optional vs. mandatory (second patch).
This patch set is cleaning this up and uses a consistent and more flexible pattern for optional / mandatory requirements.

Dracut dependency cleanup

---

dracut/30ignition/coreos-teardown-initramfs-network.service
dracut/30ignition/coreos-teardown-initramfs-network.sh
dracut/30ignition/ignition-generator
dracut/30ignition/module-setup.sh

This is a forward port of coreos-teardown-initramfs-network.service
from the spec2x branch [1] (used for RHEL CoreOS). When moving to NM
in the initrd [2] we decided that we also needed a mechanism to take down
the networking between the initramfs and the real root. While we would
like to use NetworkManager's logic to do this operation in the future
it's currently not easily achieved because NetworkManager is not running
persistently in the initramfs [3].
Additionally, we have decided to propagate initramfs networking configuration
in some scenarios [4]. The policy here is:
- If a networking configuration was provided before this point
(most likely via Ignition) and exists in the real root then
we do nothing and don't propagate any initramfs networking.
- If a user did not provide any …

add coreos-teardown-initramfs-network.service

---

dracut/30ignition/module-setup.sh

Required by the recent addition of coreos-teardown-initramfs-network.service.

Add `basename` dependency to dracut module

---

dracut/30ignition/coreos-teardown-initramfs-network.service

We want to run the teardown after all other Ignition stages
have run because some platforms (like Packet) do remote status
reporting for each Ignition stage. Since we are tearing down
the networking using an ExecStop we need to make sure we run
the ExecStop *after* any other ignition*.service unit's ExecStop.
The only other one right now is ignition-mount that has an ExecStop
for doing an unmount. Since the ordering for ExecStop is the
opposite of ExecStart we need to use `Before=ignition-mount.service`.
Partial fix for https://github.com/coreos/fedora-coreos-tracker/issues/440
This would most likely not be necessary if Ignition cached an
empty result: https://github.com/coreos/ignition/issues/950

coreos-teardown-initramfs-network: order ExecStop after other ignition units

---

dracut/99emergency-timeout/ignition-virtio-dump-journal.service
dracut/99emergency-timeout/ignition-virtio-dump-journal.sh
dracut/99emergency-timeout/module-setup.sh

Debugging failures in the initrd is annoying; this code
looks for a virtio-serial port named `com.coreos.ignition.journal`,
and runs as part of `emergency.target`.
I plan to change mantle to set up this port by default, so if
something fails in the initramfs we'll at least reliably get
the journal in a sane parsable format.
This is a special targeted subset of
https://github.com/coreos/ignition/issues/585

Add ignition-virtio-dump.service

---

systemd/ignition-firstboot-complete.service

In live boots there's no /boot partition with a flag file to remove.
(cherry picked from commit eb48c1892b5854373d8d51e84726a0876a5b6167)

[spec2x] systemd: don't try to mark live boots complete

---

dracut/30ignition/ignition-generator

Prep for backporting code that references this.  We could likely
almost get rid of the oemid bits from here if we backported
the new names into spec2x ignition too.

dracut/generator: Also write PLATFORM_ID if set

---

dracut/99emergency-timeout/ignition-virtio-dump-journal.service
dracut/99emergency-timeout/ignition-virtio-dump-journal.sh
dracut/99emergency-timeout/module-setup.sh

Debugging failures in the initrd is annoying; this code
looks for a virtio-serial port named `com.coreos.ignition.journal`,
and runs as part of `emergency.target`.
I plan to change mantle to set up this port by default, so if
something fails in the initramfs we'll at least reliably get
the journal in a sane parsable format.
This is a special targeted subset of
https://github.com/coreos/ignition/issues/585
(cherry picked from commit 84c89f4a5fa5b32c39df01e6ec5fd081050daa62)

Add ignition-virtio-dump-journal.service

---

dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-fetch.service
dracut/30ignition/ignition-files.service
dracut/30ignition/module-setup.sh

We need to order the `disks` stage after the `fetch` stage, not `setup`.
This is part of the backport of the fetch stage.
We also need to fix the order of the `fetch` stage wrt to the `setup`
service as part of the ignition-setup-{base,user} split backport.

[spec2x] 30ignition: fix ordering of fetch, disks, and files 

---

dracut/30ignition/ignition-setup-user.sh

For RHCOS, dracut mounts `/boot` in the FIPS case, and things
blow up if we try to mount it twice.
Also bigger picture at this point we have a crap ton of services
all trying to mount `/boot`; we might as well just add a `boot.mount`
unit to our initramfs.

setup-user: Accept an existing /boot mount

---

dracut/30ignition/ignition-setup-base.sh

This currently occurs in the "synthetic" RHCOS upgrade test.

setup: Do nothing if PLATFORM_ID is unset

---

dracut/30ignition/coreos-teardown-initramfs-network.sh

There are several improvements to the coreos-teardown-initramfs-network script in this patchset. The most significant are: support for propagating the hostname to the real root if it was provided via static networking ip= kargs and also adding support for the coreos.no_persist_ip karg. Please see each commit for the full details on each change.
- coreos-teardown-initramfs-network: also propagate hostname
- coreos-teardown-initramfs-network: support coreos.no_persist_ip karg
- coreos-teardown-initramfs-network: do SELinux relabel on copied files

coreos-teardown-initramfs-network: propagate hostname, support coreos.no_persist_ip

---

dracut/30ignition/ignition-generator

Outputting stdout and stderr to /dev/kmsg is the only option for
logging for generators for now. Let's start using it so we can at
least get some messages if we ever have problems with one of our
generators.

dracut: add logging to systemd generator

---

dracut/30ignition/coreos-teardown-initramfs-network.service

If another unit failed (like ignition-fetch.service) then don't run
the ExecStop when isolating to emergency.target. We can do this by
setting IgnoreOnIsolate=true.
Otherwise you end up with errors like the following in the logs,
which can lead someone investigating a problem in the wrong direction.
```
Stopping Tear down initramfs networking...
info: taking down network device: eth0
RTNETLINK answers: Operation not supported
info: flushing all routing
info: no initramfs hostname information to propagate
ls: cannot access '/sysroot/etc/NetworkManager/system-connections/': No such file or directory
ls: cannot access '/sysroot/etc/sysconfig/network-scripts/': No such file or directory
info: no networking config is defined in the real root
info: propagating initramfs networking config to the …
```

coreos-teardown-initramfs-network: don't run when emergency.target

---

dracut/30ignition/module-setup.sh

The original intent here was that on arches where `fw_cfg` is available,
then we definitely want to make sure that either it's built into the
kernel or if a module, added to the initrd. However, this check has been
watered down now to to the point where it's not that useful.
In https://github.com/coreos/ignition-dracut/issues/176, there's a
reasonable request to support not having the `qemu_fw_cfg` module
installed at all even if the architecture would support it.
IMO, I think we should just drop this whole logic entirely. The `qemu`
module (which we depend on) already does an `instmods qemu_fw_cfg`
(without `-c`), and qemu testing is the backbone of our CI testing. So
realistically, we would notice very fast if `fw_cfg` support in the
initrd went missing.
Closes: #176

30ignition: drop hard requirement on qemu_fw_cfg

---

dracut/99emergency-timeout/timeout.sh

Fix line wrapping and add line breaks.  Also remember to check `ignition-fetch.service` for failure.
See also #168; cc @cgwalters.

99emergency-timeout: improvements to failure message

---

dracut/30ignition/ignition-files.service
dracut/30ignition/ignition-remount-sysroot.service

For RHCOS https://github.com/coreos/coreos-assembler/pull/1420
broke things because `ignition-files.service` was unconditionally
pulling in `ignition-remount-sysroot.service` when it should
only be activated by `ignition-diskful.target`.
Sync things up with master here.

Sync ignition-remount-sysroot.service handling with master

---

dracut/30ignition/coreos-teardown-initramfs.service
dracut/30ignition/coreos-teardown-initramfs.sh
dracut/30ignition/module-setup.sh

Rename coreos-teardown-initramfs-network.* to
coreos-teardown-initramfs.* and add function to propagating automatic
configuration through to boot.
This requires https://github.com/dracutdevs/dracut/commit/b8a92b715677d52dbc2b27a710b9816fd8b9a63b and can be used with https://github.com/coreos/fedora-coreos-config/pull/392
Signed-off-by: Ben Howard <ben.howard@redhat.com>

coreos-teardown-initramfs: propagate the automatic multipath conf

---

dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-fetch.service
dracut/30ignition/ignition-files.service
dracut/30ignition/ignition-mount.service
dracut/30ignition/ignition-setup-base.service
dracut/30ignition/ignition-setup-user.service

Individual commit messages:
```
30ignition: clean up Ignition stages ordering 
First, put the order of the stages in every unit file. Then, make sure
to include both the appropriate `After=` and `Before=` in accordance
with the unit's place in the chain. There's redundancy there, but it
makes it really obvious and explicit how they go together.
```
```
ignition-setup-user.service: run before multipathd
This is required because the unit needs read-only access to `/boot` in
order to extract any baked in user-provided config and multipathd might
claim ownership.
See: #183
```

Cleanups and small patch for multipathd

---

dracut/30ignition/coreos-teardown-initramfs.sh
dracut/30ignition/ignition-check-neednet.sh
dracut/30ignition/ignition-disks.service
dracut/30ignition/ignition-fetch-offline.service
dracut/30ignition/ignition-files.service
dracut/30ignition/ignition-mount.service
dracut/30ignition/ignition-setup-base.service
dracut/30ignition/ignition-setup-user.service
dracut/30ignition/module-setup.sh

Make use of the new `fetch-offline` stage:
coreos/ignition#979
We run this between the `setup` and `fetch` stages (the latter possibly
being skipped if networking is not required).
We hit the same issue here that `coreos-copy-firstboot-network.service`
hit, which is that we can't run before the `cmdline` hook because that
runs *before* udev, but we want the `by-*` symlinks for
`ignition-setup-user.service`.
The hack we do here is to rerun the NM cmdline hook in case ignition
dropped a snippet in `/etc/cmdline.d`. As mentioned in
coreos/fedora-coreos-config#346, we'll be able
to do this more cleanly once we run NM as a systemd service directly.

Add new ignition-fetch-offline.service

---

Makefile

This tweaks permissions when installing units in order to avoid
the following warning at boot time:
```
systemd[1]: Configuration file /usr/lib/systemd/system/ignition-firstboot-complete.service is marked executable.
Please remove executable permission bits. Proceeding anyway.
```

make: install systemd unit as non-executable

---

dracut/30ignition/99-xx-ignition-systemd-cryptsetup.rules
dracut/30ignition/ignition-luks.conf
dracut/30ignition/module-setup.sh

Adds LUKS related binaries to dracut, a new unit that copies keyfiles
from the initramfs to the real root, a generator for unlocking clevis
devices, a udev rule to discover unformatted encrypted devices, and two
cracklib files needed by clevis in the initramfs.

*: add LUKS

---

dracut/30ignition/99-xx-ignition-systemd-cryptsetup.rules

Mistakenly the udev rule is using `:=` which is already being assumed by
udev to mean `=`. Change it to stop emitting a warning.

dracut/30ignition: fix typo in udev rule
